version: "2"
services:
  meditor:
    image: moravianlibrary/meditor
    env_file: meditor.env
    volumes:
      - /data/meditor:/data/meditor
      - imageserver:/data/imageserver
    ports:
      - "80:8080"
      - "443:8443"
  meditorPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=meditor
      - POSTGRES_PASSWORD=meditor
      - POSTGRES_DB=meditor
    ports:
      - "5432:5432"
  ldap:
    image: jirikrepl/slapd
    environment:
      -  LDAP_DOMAIN=medit.mzk.cz
      -  LDAP_ORGANISATION="MZK"
      -  LDAP_ROOTPASS=s3cr3tpassw0rd
    ports:
      - "389:389"
  kramerius:
    image: moravianlibrary/kramerius
    ports:
      - "81:8080"
    environment:
      - fedoraHost=http://fcrepo:8080/fedora
      - fedoraUser=fedoraAdmin
      - fedoraPass=fedoraAdmin
      - fedora3_connectionURL=jdbc:postgresql://fedoraPostgres:5432/fedora3
      - fedora3_connectionUser=fedoraAdmin
      - fedora3_connectionPass=fedoraAdmin
      - kramerius_connectionURL=jdbc:postgresql://krameriusPostgres:5432/kramerius
      - kramerius_connectionUser=fedoraAdmin
      - kramerius_connectionPass=fedoraAdmin
      - driver_fedora_mpt_jdbc_url=jdbc:postgresql://riTriplesPostgres:5432/riTriples
      - driver_fedora_mpt_jdbc_user=fedoraAdmin
      - driver_fedora_mpt_jdbc_password=fedoraAdmin
      - solrHost=http://solr:8080/solr
      - applicationUrl=http://kramerius:8080/search

  krameriusPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=kramerius
  fcrepo:
    image: moravianlibrary/fcrepo:3.8.1
    environment:
      - FEDORA_PASSWORD=fedoraAdmin
      - "FEDORA_DB_JDBC_URL=jdbc:postgresql://fedoraPostgres:5432/fedora3"
      - FEDORA_DB_USER=fedoraAdmin
      - FEDORA_DB_PASSWORD=fedoraAdmin
      - "RITRIPLES_DB_JDBC_URL=jdbc:postgresql://riTriplesPostgres:5432/riTriples"
      - RITRIPLES_DB_USER=fedoraAdmin
      - RITRIPLES_DB_PASSWORD=fedoraAdmin
    ports:
      - "8080:8080"
  fedoraPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=fedora3
  riTriplesPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=riTriples
  solr:
    image: moravianlibrary/solr
  nginx:
    image: moravianlibrary/iipsrv-nginx
    ports:
      - "82:80"
  memcached:
    image: memcached:latest
  iipimage:
    image: moravianlibrary/iipsrv-imageserver
    volumes:
      - imageserver:/data
volumes:
  imageserver:
